"""empty message

Revision ID: 94e0b902ba82
Revises: 
Create Date: 2022-07-11 20:15:23.068055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e0b902ba82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.String(length=20, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('userpw', sa.String(length=20, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('name', sa.String(length=20, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('email', sa.String(length=20, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('phone', sa.String(length=20, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
