"""empty message

Revision ID: ed85eab55c46
Revises: 94e0b902ba82
Create Date: 2022-07-15 13:11:42.856022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed85eab55c46'
down_revision = '94e0b902ba82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('content', sa.Text(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boards')
    # ### end Alembic commands ###
